title: Michael Heinzers blog
author: Michael Heinzer
email: heinzerm.ch@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This blog discusses various topics related to machine learning and mathematics with a focus on deep learning
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Michael Heinzer
  tagline: Mathematics and Machine Learning
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  useMathJax: true

  # generate social links in footer
  social_links:
    github:  heinzermch
    linkedIn: in/heinzerm
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture
remote_theme: thelehhman/texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
